"""Pytest fixtures for robotframework-reportlens tests."""

import pytest
from pathlib import Path


@pytest.fixture
def fixtures_dir():
    """Path to the tests/fixtures directory."""
    return Path(__file__).resolve().parent / "fixtures"


@pytest.fixture
def minimal_xml_path(fixtures_dir):
    """Path to minimal valid Robot Framework output.xml."""
    path = fixtures_dir / "minimal_output.xml"
    assert path.exists(), f"Fixture not found: {path}"
    return str(path)


@pytest.fixture
def control_structures_xml_path(fixtures_dir):
    """Path to isolated fixture output.xml with FOR/IF/TRY control structures.

    Generated by: robot --output tests/fixtures/control_structures_output.xml robot_tests/accounts.robot

    Intentionally uses isolated checked-in fixture.
    Do not use repo-root output.xml because benchmarks/tests may overwrite it.
    """
    path = fixtures_dir / "control_structures_output.xml"
    if not path.exists():
        pytest.skip(
            "control_structures_output.xml not found in tests/fixtures/ "
            "(run: robot --output tests/fixtures/control_structures_output.xml robot_tests/accounts.robot)"
        )
    return str(path)


@pytest.fixture
def html_messages_xml_path(fixtures_dir):
    """Path to output.xml with HTML (screenshot) and plain-text log messages."""
    path = fixtures_dir / "html_messages_output.xml"
    assert path.exists(), f"Fixture not found: {path}"
    return str(path)


@pytest.fixture
def sample_output_xml(tmp_path):
    """Create a minimal output.xml in a temp directory (for CLI tests)."""
    xml_content = """<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.0" generated="2026-01-31T12:00:00" rpa="false" schemaversion="5">
<suite id="s1" name="Sample" source="sample.robot">
<test id="s1-t1" name="Sample Test">
<kw name="Log" owner="BuiltIn">
<status status="PASS" start="2026-01-31T12:00:01" elapsed="0.001"/>
</kw>
<status status="PASS" start="2026-01-31T12:00:01" elapsed="0.001"/>
</test>
<status status="PASS" start="2026-01-31T12:00:01" elapsed="0.002"/>
</suite>
<statistics>
<total>
<stat pass="1" fail="0" skip="0">All Tests</stat>
</total>
</statistics>
</robot>
"""
    path = tmp_path / "output.xml"
    path.write_text(xml_content, encoding="utf-8")
    return path
